source "https://rubygems.org"

        gem 'maruku', '~> 0.7.3'
        gem 'rouge'
        gem 'normalize-rails'
        gem 'font-awesome-rails'
        gem 'font-awesome-sass', '~> 5.12.0'
        gem 'meta-tags'
        gem 'jquery-turbolinks', '2.1.0'
        gem 'mongo', '2.11.3'
        gem 'bson', '4.4.2'
        gem 'turbolinks_render'
        gem 'nokogiri', '1.10.9'
        gem 'haml', '~> 5.1', '>= 5.1.2'
        gem 'haml-rails', '~> 2.0.1'
        gem 'mail'
        gem 'prawn'
        gem 'redcarpet'
        gem 'bcrypt'
        gem 'oauth2', '1.4.4'
        gem 'omniauth', '1.9.1'
        gem 'omniauth-oauth2', '1.6.0'
        gem 'omniauth-identity', '~> 1.1.1'
        gem 'omniauth-facebook', '6.0.0'
        gem 'omniauth-google-oauth2', '0.8.0'
        gem 'dotenv-rails', '2.7.5'
        gem 'cloudinary', '1.13.2'
        gem 'kaminari', '1.2.0'
        gem 'kaminari-mongoid', '1.0.1'
        gem 'jquery-rails', '4.3.5'
          gem 'shoulda'
          gem 'rspec'
          gem 'rspec-rails'
          gem 'better_errors'
          gem 'binding_of_caller'
          gem 'pry-byebug'
          gem 'factory_bot_rails'
		      gem 'database_cleaner'
          gem 'guard'
          gem 'guard-rspec'
          gem 'guard-minitest'
          gem 'capybara'
		      gem 'selenium-webdriver'
          gem 'rb-fsevent'
		      gem 'valid_attribute'
          gem 'faker', :git => 'https://github.com/stympy/faker.git', :branch => 'master'
